/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.radio.vues;
import javax.swing.JMenuBar;
import javax.swing.JMenu;
import javax.swing.JToolBar;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import java.awt.Panel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;

import com.radio.beans.Configuration;

import javax.swing.JRadioButton;
import java.awt.Component;
import javax.swing.Box;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Window.Type;

/**
 *
 * @author amgharm
 */
public class RadioGui extends javax.swing.JFrame {

	public static Configuration configurationRadio = new Configuration();
    /**
     * Creates new form NewJFrame
     */
    public RadioGui() {
    	setType(Type.UTILITY);
    	setTitle("Configuration");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        JRadioButton radioButtonRHOn = new JRadioButton("");
        radioButtonRHOn.setSelected(RadioGui.configurationRadio.getRechercheAuto().isEtat());
        
        JLabel lblNewLabel_2 = new JLabel("Oui");
        
        JLabel lblNewLabel_3 = new JLabel("Non");
        
        JRadioButton radioButtonRHOff = new JRadioButton("");
        radioButtonRHOff.setSelected(!RadioGui.configurationRadio.getRechercheAuto().isEtat());
        
        JLabel lblNewLabel = new JLabel("Réglage automatique");
        
        JLabel lblNewLabel_1 = new JLabel("Haut-parleur secondaire");
        
        JLabel lblNewLabel_4 = new JLabel("Sortie audio externe");
        
        JLabel lblNewLabel_5 = new JLabel("Entrée audio externe");
        
        JLabel lblNewLabel_6 = new JLabel("Date et Heure automatique");
        
        JLabel lblNewLabel_7 = new JLabel("Horloge automatique");
        
        JLabel lblNewLabel_8 = new JLabel("Breaking news");
        
        JLabel lblNewLabel_9 = new JLabel("Radio FM");
        
        JRadioButton radioButtonHTOn = new JRadioButton("");
        radioButtonHTOn.setSelected(configurationRadio.getRechercheAuto().isEtat());
        
        JRadioButton radioButtonHTOff = new JRadioButton("");
        radioButtonHTOff.setSelected(!configurationRadio.getRechercheAuto().isEtat());
        
        JRadioButton radioButtonSEOn = new JRadioButton("");
        radioButtonSEOn.setSelected(RadioGui.configurationRadio.getSortieAudioExterne().isEtat());
        
        JRadioButton radioButtonSEOff = new JRadioButton("");
        radioButtonSEOff.setSelected(!RadioGui.configurationRadio.getSortieAudioExterne().isEtat());
        
        JRadioButton radioButtonEEOn = new JRadioButton("");
        radioButtonEEOn.setSelected(RadioGui.configurationRadio.getEntreeAudioExterne().isEtat());
        
        JRadioButton radioButtonEEOff = new JRadioButton("");
        radioButtonEEOff.setSelected(!RadioGui.configurationRadio.getEntreeAudioExterne().isEtat());
        
        JRadioButton radioButtonHorlogeOn = new JRadioButton("");
        radioButtonHorlogeOn.setSelected(RadioGui.configurationRadio.getHorloge().isEtat());
        
        JRadioButton radioButtonHorlogeOff = new JRadioButton("");
        radioButtonHorlogeOff.setSelected(!RadioGui.configurationRadio.getHorloge().isEtat());
        
        JRadioButton radioButtonReveilOn = new JRadioButton("");
        radioButtonReveilOn.setSelected(RadioGui.configurationRadio.getReveil().isEtat());
        
        JRadioButton radioButtonReveilOff = new JRadioButton("");
        radioButtonReveilOff.setSelected(!RadioGui.configurationRadio.getReveil().isEtat());
        
        JRadioButton radioButtonBNOn = new JRadioButton("");
        radioButtonBNOn.setSelected(RadioGui.configurationRadio.getBreakingNews().isEtat());
        
        JRadioButton radioButtonBNOff = new JRadioButton("");
        radioButtonBNOff.setSelected(!RadioGui.configurationRadio.getBreakingNews().isEtat());
        
        JRadioButton radioButtonRMOn = new JRadioButton("");
        radioButtonRMOn.setSelected(RadioGui.configurationRadio.getRadioFM().isEtat());
        
        JRadioButton radioButtonRMOff = new JRadioButton("");
        radioButtonRMOff.setSelected(!RadioGui.configurationRadio.getRadioFM().isEtat());
        
        JButton btnNewButton = new JButton("Sauvegarder");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(40, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(lblNewLabel)
        						.addComponent(lblNewLabel_1)
        						.addComponent(lblNewLabel_4)
        						.addComponent(lblNewLabel_5)
        						.addComponent(lblNewLabel_6)
        						.addComponent(lblNewLabel_7)
        						.addComponent(lblNewLabel_8)
        						.addComponent(lblNewLabel_9))
        					.addGap(60)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(lblNewLabel_2)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(lblNewLabel_3))
        						.addGroup(layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(radioButtonRHOn)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(radioButtonRHOff))
        						.addGroup(layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(radioButtonSEOn)
        									.addPreferredGap(ComponentPlacement.UNRELATED)
        									.addComponent(radioButtonSEOff))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(radioButtonHTOn)
        									.addPreferredGap(ComponentPlacement.UNRELATED)
        									.addComponent(radioButtonHTOff))
        								.addGroup(layout.createSequentialGroup()
        									.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        										.addComponent(radioButtonHorlogeOn)
        										.addComponent(radioButtonEEOn)
        										.addComponent(radioButtonReveilOn)
        										.addComponent(radioButtonBNOn)
        										.addComponent(radioButtonRMOn))
        									.addPreferredGap(ComponentPlacement.UNRELATED)
        									.addGroup(layout.createParallelGroup(Alignment.LEADING)
        										.addComponent(radioButtonRMOff)
        										.addComponent(radioButtonBNOff)
        										.addComponent(radioButtonReveilOff)
        										.addComponent(radioButtonHorlogeOff)
        										.addComponent(radioButtonEEOff))))))
        					.addContainerGap())
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addComponent(btnNewButton)
        					.addGap(86))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lblNewLabel_2)
        						.addComponent(lblNewLabel_3))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(radioButtonRHOn)
        						.addComponent(radioButtonRHOff)))
        				.addComponent(lblNewLabel))
        			.addGap(13)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(lblNewLabel_1)
        				.addComponent(radioButtonHTOn)
        				.addComponent(radioButtonHTOff))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createParallelGroup(Alignment.LEADING)
        					.addComponent(radioButtonSEOff)
        					.addComponent(radioButtonSEOn))
        				.addComponent(lblNewLabel_4))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(radioButtonEEOn)
        				.addComponent(radioButtonEEOff)
        				.addComponent(lblNewLabel_5))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        					.addComponent(lblNewLabel_6)
        					.addComponent(radioButtonHorlogeOn))
        				.addComponent(radioButtonHorlogeOff))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(radioButtonReveilOn)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(4)
        					.addComponent(lblNewLabel_7))
        				.addComponent(radioButtonReveilOff))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(radioButtonBNOff)
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(radioButtonRMOff))
        				.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        					.addComponent(lblNewLabel_9)
        					.addGroup(layout.createSequentialGroup()
        						.addGroup(layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(radioButtonBNOn)
        							.addGroup(layout.createSequentialGroup()
        								.addGap(4)
        								.addComponent(lblNewLabel_8)))
        						.addPreferredGap(ComponentPlacement.UNRELATED)
        						.addComponent(radioButtonRMOn))))
        			.addGap(46)
        			.addComponent(btnNewButton)
        			.addGap(183))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioGui().setVisible(true);
            }
        });
    }
}
